@startuml
title Update a Provider

actor Admin
participant "Express Server" as Server
participant "Provider Router" as Router
participant "Provider Controller" as Controller
participant "Provider Model" as Model
database "«MongoDB»\n:providers" as Database

Admin -> Server: POST /api/v1/providers
Server -> Router: app.use('/api/v1/providers', providers)
Router -> Controller: updateProvider(req.body)
Controller -> Model: findOne({ email })
alt new Email already exists
    Controller -> Server: Response 400 (Email already registered)
    Server -> Admin: Response 400 (Email already registered)
else Email is unique or Email not being updated
    Controller -> Model: create(req.body)
    Model -> Database: ProviderSchema
    Database --> Model: return updated Provider
    Model --> Controller: return updated Provider
    Controller -> Server: Response 201 (Provider created)
    Server -> Admin: Response 201 (Provider created)
end
@enduml
